version: '3'
services:

# Web tier
  meuapp:
    build: .
    depends_on:
       - meudb
       - meucache
    restart: always
    #container_name: webserver
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - net-meuapp
    volumes:
      - ./src:/var/www/html
    links:
      - meudb
      - meucache

# Database tier
  meudb:
    image: mysql:latest
    restart: always
    #container_name: dbserver
    environment: 
      MYSQL_DATABASE: 'meubanco'
      MYSQL_USER: 'meuuser'
      MYSQL_PASSWORD: 'meupass10'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
    ports:
      - '3306:3306'
    networks:
      - net-meuapp
    volumes:
      - vol-db:/var/lib/mysql
      - ./src/meuapp.sql:/docker-entrypoint-initdb.d/meuapp.sql

# Cache tier
  meucache:
    image: redis:latest
    restart: always
    #container_name: cacheserver
    ports:
      - '63791:6379'
    networks:
      - net-meuapp
    volumes:
      - vol-cache:/var/lib/redis
 
# Networks
networks:
  net-meuapp:
    driver: bridge
    
# Volumes
volumes:
  vol-db:
    #external: true
  vol-cache:
